apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common

patchesStrategicMerge:
  - service-prod.yaml
  - deployment-prod.yaml
  - ingress-prod.yaml

namespace: prod