apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common

patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    path: ingress-prod.yaml
  # - target:
  #     kind: Service
  #     name: nginx-service
  #   path: service-prod.yaml
  - target:
      kind: Deployment
      name: nginx
    path: deployment-prod.yaml

namespace: prod