apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common

patches:
  - path: ingress-prod.yaml
  - path: service-prod.yaml
  - path: deployment-prod.yaml

namespace: prod