pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'docker.io/engsabry/nginx-argo'
        DOCKER_IMAGE_TAG = 'latest'
        DOCKER_CREDENTIALS_ID = 'dockerhub-token' 
        GITHUB_CREDENTIALS_ID = 'github-pat' 
    }

    stages {
        stage('Code Checkout') {
            steps {
                echo 'Checking out code...'
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']], 
                    userRemoteConfigs: [[
                        url: 'https://github.com/OpsMo/argocd-app.git',
                        credentialsId: GITHUB_CREDENTIALS_ID
                    ]]
                ])
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
                    docker.build("$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG", '.')
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    echo "Pushing Docker image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        docker.image("$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG").push()
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}