kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80≈