apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common

patches:
  - path: ingress-dev.yaml
  - path: service-dev.yaml
  - path: deployment-dev.yaml

namespace: dev