apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common

patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    path: ingress-dev.yaml
  - target:
      kind: Service
      name: nginx-service
    path: service-dev.yaml
  - target:
      kind: Deployment
      name: nginx
    path: deployment-dev.yaml

namespace: dev